# src/main/resources/application.yml
spring:
  profiles:
    active: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
        show_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL}
        use_sql_comments: ${SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS}
        hbm2ddl:
          auto: ${SPRING_JPA_PROPERTIES_HIBERNATE_HBM2DDL_AUTO}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE}
    sql-migration-suffixes: ${SPRING_FLYWAY_SQL_MIGRATION_SUFFIXES}
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}

jwt:
  header: ${JWT_HEADER}
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  allowed-clock-skew-seconds: ${JWT_ALLOWED_CLOCK_SKEW_SECONDS}
  token-validity-in-seconds: ${JWT_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

oauth:
  kakao:
    app-id: ${OAUTH_KAKAO_APP_ID}
    rest-api-key: ${OAUTH_KAKAO_REST_API_KEY}
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    redirect-url: ${OAUTH_KAKAO_REDIRECT_URL}
    base-url: ${OAUTH_KAKAO_BASE_URL}

springdoc:
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
