ALTER TABLE chat_room
    ADD COLUMN updated_at DATETIME(6) DEFAULT NULL;

ALTER TABLE chat_message
    ADD COLUMN updated_at DATETIME(6) DEFAULT NULL;

ALTER TABLE chat_participant
    ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN updated_at DATETIME(6) DEFAULT NULL;

ALTER TABLE chat_message_reaction
    ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN updated_at DATETIME(6) DEFAULT NULL;
